const actionTypes = {
  SET_USER: "SET_USER",
  SET_POSTS: "SET_POSTS",
  SET_AUTH: "SET_AUTH",
  SET_OPEN: "SET_OPEN",
  SET_OPEN_SIGN_IN: "SET_OPEN_SIGN_IN",
  SET_PASSWORD: "SET_PASSWORD",
  SET_EMAIL: "SET_EMAIL",
  SET_USERNAME: "SET_USERNAME",
  SET_SCROLL: "SET_SCROLL",
  SET_OPEN_UPLOAD: "SET_OPEN_UPLOAD",
};

export { actionTypes };
